{% set name = "pyGSTi" %}
{% set version = "0.9.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyGSTi-{{ version }}.tar.gz
  sha256: 602457b54b31d32545113b41b7b4c6d5453b2ec384badf2b745b246b9c723cb0

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - cython
    - numpy
    - pip
  run:
    - python
    - scipy
    - plotly
    - pandas

test:
  imports:
    - pygsti
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.pygsti.info
  summary: A python implementation of Gate Set Tomography
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - enielse
