schema_version: 1

context:
  name: pyGSTi
  version: 0.9.13

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyGSTi-${{ version }}.tar.gz
  sha256: 99b7ec1021087a4e4d2babff4cc035607eabf7a7bc94b228d45e98b95d4208ce

build:
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - cython
    - numpy
    - pip
  run:
    - python
    - scipy
    - plotly
    - pandas
    - networkx
    - ${{ pin_compatible('numpy') }}
    # Not in the required dependencies of pyGSTi, but importing pyGSTi requires it
    - matplotlib-base

tests:
  - python:
      imports:
        - pygsti

about:
  homepage: http://www.pygsti.info
  summary: A python implementation of Gate Set Tomography
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - enielse
